name: Publish to PyPI

on:
  push:
    #tags:
      #- "v*"  # Trigger only on versioned tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Use Python 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
      
      - name: Install dependencies
        run: |
          pwd && find .
      
      - name: Build the package
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
        working-directory: ./markitanalysis  # Adjust if `setup.py` is in a subdirectory

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --verbose dist/*
        working-directory: ./markitanalysis  # Adjust if `dist` is in a subdirectory
